// Angular/apAngular/src/app/app.component.ts
import { Component } from '@angular/core';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css']
})
export class AppComponent {
  peso = null;
  altura = null;
  imc = null;
  filteredText = null;
  selected = null;
  txtFilter = null;

  
  public calculateIMC() {
    if(this.peso == null || this.altura == null) return
    if(!this.altura.match(/^[0-9]+$/) || !this.peso.match(/^[0-9]+$/)) {
      this.altura = null
      this.peso = null
      alert ('Escreva apenas numeros inteiros!')
      return
    }
    let alturaCalculo = this.altura
    alturaCalculo = this.altura/100
    this.imc = this.peso / (alturaCalculo * alturaCalculo)
  }

  public filterText(){
    if(this.txtFilter == '') return
    if(this.selected == '') return
    if(this.selected == 'Consoantes'){
      this.filteredText = this.txtFilter.replace(/[A|E|I|O|U]/ig, "")
    } else {
      this.filteredText = this.txtFilter.replace(/[^A|E|I|O|U]/ig, "")
    }
  }
}

<div style="width: 50%; justify-content: center;">
  <div>
    <span><h3>Cálculo de IMC</h3></span>
    <span><h4>Digite apenas numeros inteiros</h4></span>
    <div><span>Peso      :   </span>
      <input type="text" placeholder="Digite o Peso" [value]="peso" (input)="peso = $event.target.value" /></div>
      <div><span>Altura: </span>
    <input type="text" placeholder="Digite a Altura" [value]="altura" (input)="altura = $event.target.value"  /></div>
  <button (click)="calculateIMC()">Calcular IMC</button> <br />
  <span><h4>Seu IMC é: {{ imc }}</h4></span><br>
  </div>
  <br /><br />
  ------------------------------------------------------------------------------------------------
  <div><br><br>
    <span><h3>Filtro de consoantes/vogais</h3></span>
    <span><h4>Digite o Texto</h4></span>
    <div><span>Texto Completo:   </span><input placeholder="Digite algum texto" [value]="txtFilter" (input)="txtFilter = $event.target.value"></div>
    <div><span>Escolha o Modo:   </span><select [value]="selected" (input)="selected = $event.target.value">
      <option disabled value="">Escolha um item</option>
      <option>Vogais</option>
      <option>Consoantes</option>
    </select></div>
    <button (click)="filterText()">Filtrar Texto</button> <br />
    <span><h4>Texto Filtrado: {{ filteredText }}</h4></span><br>
    
  </div>

</div>

// React/my-app/src/App.js
import React, { useState } from 'react';
import './App.css';

function App() {
  const [imc, setImc] = useState()
  const [filteredText, setFilteredText] = useState()
  const [peso, setPeso] = useState()
  const [altura, setAltura] = useState()
  const [txtFilter, setTxtFilter] = useState()
  const [selected, setSelected] = useState()

  const changeText = () => {

  }

  const calculateIMC = () => {
    if(peso == 0 || peso == false || altura == 0 || altura == false) return
    let alturaCalculo = altura
    alturaCalculo = altura/100
    let calculoImc = peso / (alturaCalculo * alturaCalculo)
    setImc(calculoImc)
  }

  
  const filterText = () =>{
    let aux = ''
    if(txtFilter == '' || txtFilter == false) return
    if(selected == '' || selected == false) return
    if(selected == 'Consoantes'){
      aux = txtFilter.replace(/[A|E|I|O|U]/ig, "")
    } else {
      aux = txtFilter.replace(/[^A|E|I|O|U]/ig, "")
    }
    setFilteredText(aux)
  }

  return (
    <div className="App">
        <div>
        <div>
          <span><h3>Cálculo de IMC</h3></span>
          <span><h4>Digite apenas numeros inteiros</h4></span>
          <div><span>Peso   : </span><input type="text" value={peso} placeholder="Digite o Peso" onChange={e => setPeso(e.target.value)}/></div>
          <div><span>Altura: </span><input type="text" value={altura} placeholder="Digite a Altura" onChange={e => setAltura(e.target.value)}/></div>
          <button onClick={calculateIMC}>Calcular IMC</button> <br />
          <span><h4>Seu IMC é: { imc }</h4></span><br />
        </div>
        <br /><br />
        ------------------------------------------------------------------------------------------------
        <div><br /><br />
          <span><h3>Filtro de consoantes/vogais</h3></span>
          <span><h4>Digite o Texto</h4></span>
          <div><span>Texto Completo:</span><input type="text" value={txtFilter} placeholder="Digite algum texto" onChange={e => setTxtFilter(e.target.value)}/><br /></div>
          <div><span>Escolha o Modo:</span><select value={selected} onChange={e => setSelected(e.target.value)} style={{ width: 170 + "px" }}> 
            <option disabled value="" >Escolha um item</option>
            <option>Vogais</option>
            <option>Consoantes</option>
          </select></div>
          <button onClick={filterText}>Filtrar Texto</button> <br />
        <span><h4>Texto Filtrado: { filteredText }</h4></span><br />
          
        </div>
      </div>
    </div>
  );
}

export default App;
